### ISSUE TITLE
New graph in reports (develop)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#770]
Hello!

The new graph library integrated in last develop needs several adjustments.

- We lost 3D PIE.
- % placement need adjustments (see screen shot)
- Title font size is too small.
- The legends in my opinion were easier to read before (on the right, one below the others).
- We don't need to have % in legend text as it's already printed in PIE.

![capture d ecran 2017-05-02 a 09 26 00](https://cloud.githubusercontent.com/assets/12907102/25608202/50ea0f4c-2f1a-11e7-9653-5b1694ca3cc0.png)

On more. When we print the graph or generate a PDF, the array lines are missing. This is not very important but it is still more beautiful and easier to read with lines.

![capture d ecran 2017-05-02 a 09 34 38](https://cloud.githubusercontent.com/assets/12907102/25608384/e85a09d6-2f1a-11e7-91fc-088f3b0831b5.png)

**Comment by asuweb** [comment]
I like these new charts. Excellent work @Skywalker-11 (at least I think it was you).

The also load in record time.  Perfect.  For me 3d isn't an issue, but some may wish it.

**Comment by Skywalker-11** [comment]
The percentages should be fixed with #797. @stefaweb can you try it?

**Comment by stefaweb** [comment]
Hello @Skywalker-11!

Will try later.

Found 2 others problems (last develop).

![capture d ecran 2017-05-20 a 21 05 39](https://cloud.githubusercontent.com/assets/12907102/26278661/503a383a-3da0-11e7-955e-8322c8bb215a.png)

![capture d ecran 2017-05-20 a 21 06 09](https://cloud.githubusercontent.com/assets/12907102/26278662/543e3d32-3da0-11e7-88f9-9ac628b56f90.png)

**Comment by Skywalker-11** [comment]
Total mail hasn't been updated for Chart.js yet.
The problem with undefined offset should be fixed in pr. Problem was old variable name that wasn't updated when moving to Chart.js
The problem with mail size not being formatted has been added to that pr.

**Comment by stefaweb** [comment]
> Total mail hasn't been updated for Chart.js yet.

Something have changed between 1.2.2 and develop.

1.2.2
![total_mail_by_date png 1495433486](https://cloud.githubusercontent.com/assets/12907102/26294768/7abacee0-3ec6-11e7-9c00-319463481136.png)

develop
![503a383a-3da0-11e7-955e-8322c8bb215a](https://cloud.githubusercontent.com/assets/12907102/26294766/77d450a2-3ec6-11e7-8eae-4a31c5915eb5.png)

**Comment by Skywalker-11** [comment]
The only thing that changed is that we fixed the order in which the filter.inc.php and functions.php is included (see below). 
Also it is looking like in 1.2.2 here with current develop. Maybe the "problem" is that you generated the graph for 2 month in 1.2.2 and for 4 month in develop?
![image](https://cloud.githubusercontent.com/assets/11180862/26297627/f43cc23e-3ed3-11e7-9985-8161349bb35a.png)

```
$ git diff upstream/develop mailscanner/rep_total_mail_by_date.php
diff --git a/mailscanner/rep_total_mail_by_date.php b/mailscanner/rep_total_mail_by_date.php
index f888248..2142881 100644
--- a/mailscanner/rep_total_mail_by_date.php
+++ b/mailscanner/rep_total_mail_by_date.php
@@ -30,10 +30,11 @@
  */

 // Include of necessary functions
-require_once __DIR__ . '/filter.inc.php';
 require_once __DIR__ . '/functions.php';
+require_once __DIR__ . '/filter.inc.php';

 // Authentication checking
+session_start();
 require __DIR__ . '/login.function.php';

 // add the header information such as the logo, search, menu, ....
```

**Comment by stefaweb** [comment]
You're right.

Something seems wrong with my develop version.

![capture d ecran 2017-05-22 a 10 57 22](https://cloud.githubusercontent.com/assets/12907102/26300161/9b880a2c-3edd-11e7-8f9e-802ec316e66c.png)

But I have: `define('RECORD_DAYS_TO_KEEP', 60);`

Running mailwatch_db_clean.php manual, don't change the problem.

**Comment by Skywalker-11** [comment]
Can you look in your mtalog if there are older mails and then try to run 
```
            'DELETE i, m FROM mtalog AS m
             JOIN mtalog_ids AS i ON i.smtp_id = m.msg_id
             WHERE m.timestamp < (NOW() - INTERVAL ' . RECORD_DAYS_TO_KEEP . ' DAY)'
```
and check again?

**Comment by stefaweb** [comment]
mtalog and mtalog_ids are empty. I use Exim.

**Comment by stefaweb** [comment]
In maillog, the oldest record is like this:

```
timestamp: 2017-03-23 20:10:54
date: 2017-01-22
time: 18:14:51
```

**Comment by stefaweb** [comment]
Opened a specific issue on this: #800

**Comment by Skywalker-11** [comment]
mailwatch_db_clean only deletes from mtalog 😁

**Comment by stefaweb** [comment]
Sorry, I'm lost.  🙃

**Comment by Skywalker-11** [comment]
Problem is probably here: line 197-205 in rep_total_mail_by_date.php
```
 // Reduce the number of labels on the graph to prevent them being sqashed.
    if (count($graph_labels) > 20) {
        $b = substr(count($graph_labels), 0, 1);
        for ($a = 0, $graphLabelsCount = count($graph_labels); $a < $graphLabelsCount; $a++) {
            if ($a % $b) {
                $graph_labels[$a] = '';
            }
        }
    }
```

**Comment by stefaweb** [comment]
With last develop.

When we go on reports.php and inside report pages.

`Warning: Invalid argument supplied for foreach() in /var/www/html/mailscanner/filter.inc.php on line 208
`

Total message now work.

![total_mail_by_date png 1495624891](https://cloud.githubusercontent.com/assets/12907102/26401015/10cc2384-4084-11e7-91cc-59b2bb1821ea.png)

**Comment by stefaweb** [comment]
The new graph library integrated in last develop needs several adjustments.

> % placement need adjustments (see screen shot)

OK

> We don't need to have % in legend text as it's already printed in PIE.

OK

**Comment by stefaweb** [comment]
You still need to look at this:

- a space between the scare and the email, may be removed the % as already printed in PIE.
![capture d ecran 2017-05-24 a 13 28 48](https://cloud.githubusercontent.com/assets/12907102/26401197/084fca20-4085-11e7-8dfd-66e6ddffb325.png)

- adjust graph title font size according to others graphs.
![capture d ecran 2017-05-24 a 13 28 54](https://cloud.githubusercontent.com/assets/12907102/26401240/45787e4c-4085-11e7-9210-be62c2f956d2.png)

**Comment by Skywalker-11** [comment]
> When we go on reports.php and inside report pages.
> Warning: Invalid argument supplied for foreach() in /var/www/html/mailscanner/filter.inc.php on line 208

fix in #805

**Comment by stefaweb** [comment]
and in rep_total_mail_by_date.php. ;)

`Warning: Invalid argument supplied for foreach() in /var/www/html/mailscanner/filter.inc.php on line 193`

**Comment by Skywalker-11** [comment]
> a space between the scare and the email, may be removed the % as already printed in PIE.
> adjust graph title font size according to others graphs.
done in #806

**Comment by stefaweb** [comment]
Still a problem with space before colon (colon99 missing somewhere).

![capture d ecran 2017-05-24 a 16 12 57](https://cloud.githubusercontent.com/assets/12907102/26407767/45f097da-409c-11e7-8409-d2fa04a2acf3.png)

Also found a funny bug.
![capture d ecran 2017-05-24 a 16 18 28](https://cloud.githubusercontent.com/assets/12907102/26408042/0b99bff2-409d-11e7-922e-1a5a89f17e83.png)

Do you plan to convert rep_top_mail_relays.php and /rep_total_mail_by_date.php?

**Comment by Skywalker-11** [comment]
The plan is to convert all of them😁

**Comment by Skywalker-11** [comment]
The colon is is only " :" in fr not in en 😁 
Problem with percentages will be fixed by #807

**Comment by stefaweb** [comment]
> The colon is is only " :" in fr not in en
Sorry, I was tired. Works fine with French language.

**Comment by stefaweb** [comment]
Found another problem with round.

In light blue pie, % is missing OR in green, % should not be there.

![capture d ecran 2017-05-31 a 14 04 07](https://cloud.githubusercontent.com/assets/12907102/26631212/4d3ac236-460a-11e7-93d7-e80cb91537ce.png)

**Comment by Skywalker-11** [comment]
I used js toFixed() function [https://www.w3schools.com/jsref/jsref_tofixed.asp](https://www.w3schools.com/jsref/jsref_tofixed.asp) to get the percentage in the tooltip which rounds the value up. To see if it should always be drawn I use the precise value.

**Comment by Skywalker-11** [comment]
First preview of line Graphs :smile: 

![image](https://cloud.githubusercontent.com/assets/11180862/26637331/7c599762-461f-11e7-8a28-9f35e8aef4c5.png)

**Comment by Skywalker-11** [comment]
Line graphs are here: #824

**Comment by Skywalker-11** [comment]
#828 fixes virus graphs
Looking into that other right now

**Comment by Skywalker-11** [comment]
I only used the total mail number and overlooked the other ones :smile: 
The current version of the pr should fix that and some other warning/notices that I noticed

**Comment by Skywalker-11** [comment]
Is anyone using MCP and can provide some testing data for the graphes?

**Comment by stefaweb** [comment]
Last develop.

MCP is here unless MCP is not activated.

![capture d ecran 2017-06-06 a 08 19 34](https://cloud.githubusercontent.com/assets/12907102/26816261/16fea5da-4a91-11e7-98e3-898335ba9073.png)

**Comment by Skywalker-11** [comment]
Yes was debug code will be removed by new PR

**Comment by stefaweb** [comment]
Found only a small problem with last develop.

Could you reduce space between the graph and the legend?

Have the same distance than for Volume.

![capture d ecran 2017-06-07 a 13 11 33](https://user-images.githubusercontent.com/12907102/26876069-dd302a1e-4b84-11e7-9792-b67aca9b58ae.png)

![capture d ecran 2017-06-07 a 13 11 22](https://user-images.githubusercontent.com/12907102/26876079-e9374a2c-4b84-11e7-94d8-e8165776f3f6.png)

![capture d ecran 2017-06-07 a 13 11 54](https://user-images.githubusercontent.com/12907102/26876083-ebb92072-4b84-11e7-868a-7014388bcd8a.png)

From a general point of view, the colors are too "palish" for me.

**Comment by Skywalker-11** [comment]
I think they are the same colors as JpGraph used but we can change them. Colors are in lib/lineConfig.js and lib/pieConfig.js at the top the files in hex format

**Comment by Skywalker-11** [comment]
Can you try #837 for the xaxis?

**Comment by stefaweb** [comment]
Works great.

![capture d ecran 2017-06-07 a 15 38 17](https://user-images.githubusercontent.com/12907102/26881358-7b432690-4b97-11e7-9627-c8fb1471ad32.png)

**Comment by stefaweb** [comment]
For all PIE, will be nice to add a space line between the pie and the table.

![capture d ecran 2017-06-07 a 15 44 40](https://user-images.githubusercontent.com/12907102/26881684-70ecc6fa-4b98-11e7-900e-e2bb1b8ad19d.png)

**Comment by Skywalker-11** [comment]
done

**Comment by stefaweb** [comment]
Problem...

![capture d ecran 2017-06-07 a 20 36 28](https://user-images.githubusercontent.com/12907102/26895246-51a78888-4bc1-11e7-8f7e-5faf476584d1.png)

![capture d ecran 2017-06-07 a 20 38 19](https://user-images.githubusercontent.com/12907102/26895256-59765918-4bc1-11e7-857c-04cd4f217344.png)

**Comment by Skywalker-11** [comment]
That should be translation.So yes

**Comment by Skywalker-11** [comment]
viruscount36

**Comment by stefaweb** [comment]
Yes in en.php only, I've forgot to remove the dot.

'viruscount36' => 'Number of viruses',

**Comment by stefaweb** [comment]
> 'viruscount36' => 'Number of viruses',

Done in #839.

**Comment by Skywalker-11** [comment]
@stefaweb is the problem with the graph was in Chart.min.js where i changed the wrong part when doing it again for a clean diff.
#840 solves this

**Comment by stefaweb** [comment]
Great. New version works fine.

**Comment by Skywalker-11** [comment]
#843 changes rep_mcp_score_dist.php to Chart.js and removes the JpGraph library

**Comment by stefaweb** [comment]
Not really important but cosmetic.

Do you have the possibility to leave space at the top of the graph so that the bars do not tap against the frame?

![capture d ecran 2017-06-12 a 10 52 16](https://user-images.githubusercontent.com/12907102/27026297-922345c4-4f5d-11e7-8eb0-03c9aca47c46.png)

![capture d ecran 2017-06-12 a 10 52 04](https://user-images.githubusercontent.com/12907102/27026303-974e080e-4f5d-11e7-907b-dc2f9ae6bcbe.png)

**Comment by stefaweb** [comment]
Something new with last develop!

![capture d ecran 2017-06-13 a 15 24 40](https://user-images.githubusercontent.com/12907102/27084546-93402018-504c-11e7-8ca6-44f90462b1f6.png)
![capture d ecran 2017-06-13 a 15 24 24](https://user-images.githubusercontent.com/12907102/27084547-9348756a-504c-11e7-8389-95ccfae79fb5.png)

**Comment by Skywalker-11** [comment]
Already found that and also the messages aren't not always assigned to the right hour. Preparing the other right now and it will be fixed by that pr

**Comment by Skywalker-11** [comment]
should be fixed with pr #855

**Comment by stefaweb** [comment]
All seems fine. I can close?

**Comment by stefaweb** [comment]
Nobody commented.
I close.
