### ISSUE TITLE
Unsecure user management for domain admins

### ISSUE THREAD

**Issue by z-jun** [mailwatch/MailWatch#940]
Any domain admin without user part (before @) in username can:

- create new and modify domain admin and user acounts without user part(before @)
- change properties of admin account ( ie. downgrade type from admin to domain admin)
- delete admin account

Any domain admin EVEN with full username(user@domain.tld) can create new user with username @domain.tld and subsequently escalate privileges to other domains.

### Version and method
 - MailWatch Version: stable 1.2.5
 - Install type: Zip/tarball install
 - Updated from an older MailWatch or fresh install: Fresh install

### Server configuration
- Operation System: gentoo
- Postfix Version: 3.1.6 
- MailScanner Version: 5.0.3
- SpamAssassin Version: 3.4.1 
- PHP Version: 7.1.8
- MySQL Version: 10.1.26-MariaDB

### Client configuration 
any combination

**Comment by asuweb** [comment]
I'm fairly sure we've previously fixed this issue - so it looks like a regression bug.  Will fix again

**Comment by Skywalker-11** [comment]
It is intended that a domain admin can create other domain admins for his own domain but he can not create users for other domains. Eg if you create a domain admin "test@example.org" that user can not create a domain admin "test@example.com". But he could create a domain admin "test2@example.org".

**Comment by Skywalker-11** [comment]
@z-jun does this explain your issue or did you mean something else?

**Comment by z-jun** [comment]
@Skywalker-11 That's how it should work.

But in last version domain admin is able to create user "@own_domain.tld" which is a problem. Such user may subsequently change/delete main admin account and create/manage "super" accounts for other domains and so control them. "super" means user account in form "domain.tld".

**Comment by asuweb** [comment]
@z-jun I've fixed this in PR #945

**Comment by asuweb** [comment]
@Skywalker-11 - the issue was we weren't preventing domain admins from viewing Administrator accounts - and thus they were able to downgrade an admin account to a lower account.

**Comment by Skywalker-11** [comment]
Yes I looked into it and your PR doesn't solve all issues that are related to this. I've send a patch to @endelwar (security@mailwatch.org) that fixes them but I wasn't sure if we should handle the issue in the default way

**Comment by z-jun** [comment]
right solution is to stop detecting access rights from username string and properly sanitize username and filters while parsing/building domain filter.

**Comment by shawniverson** [comment]
@z-jun I'll add that "For all users other than Administrator you must use an email address for the username" should be enforced.  Several of these issues can be eliminated by just enforcing a valid email address via field validation.

**Comment by shawniverson** [comment]
@Skywalker-11 I have also a patch ready.  Please reach out to me if you want to compare notes.  IRC freenode.org #efa-project.org channel.

**Comment by shawniverson** [comment]
I have also emailed security@mailwatch.org a version of a fix.

**Comment by shawniverson** [comment]
P.S I'm spammy

**Comment by shawniverson** [comment]
@Skywalker-11 P.S I'm spammy....saw you pop in briefly.

**Comment by shawniverson** [comment]
Opening an item of debate here.

Should domain admins be able to modify other domain admins in the same domain?

Case in point....

Domain Admin 1 has a beef with Domain Admin 2

As it stands right now, Domain Admins can degrade other domain admins, so Domain Admin 1 can degrade (make a user) Domain Admin 2.

My vote is to take away this privilege from Domain Admins.  Basically Domain Admins should have modification rights to regular users in their own domain only to prevent security issues, period.  This should be the right of a global admin to create/modify/destroy domain admins.

I looked at a few other products, and such "power users" do not have the ability to create/modify/delete other users of the same level.

Feedback is welcome.

**Comment by stefaweb** [comment]
Hello!
Completely agree with you @shawniverson.

**Comment by asuweb** [comment]
@shawniverson - I agree also.  I also agree that domain admins should be in the form of something@domain.com
